### ISSUE TITLE
Outputting optimal hyperparameters of xgboost chosen after a few iterations.

### ISSUE THREAD

**Issue by jennyjyounglee** [fasrc/CausalGPS#122]
After few iteration of the method, we get to select hyperparameters that gives lowest mean covariate balance. However, the model output include what were the optimal hyperparameters that was chosen. This seems to be available only through log file and have to manually search line by line to find out what were the optimal hyperparameter.

It would be great to output the optimal hyperparameters of xgboost,

**Comment by Naeemkh** [comment]
@jennyjyounglee, you can get the optimal parameters by `best_gps_used_params` in the pseudo population object.
