### ISSUE TITLE
Issue with Package Installation on Mac

### ISSUE THREAD

**Issue by fbargaglistoffi** [fasrc/CausalGPS#132]
I am running into an error when trying to install the package on my Mac. Yhe problem comes from the installation of the dependency “mnormt”. The error in particular is “ld: library not found for -lgfortran”. I checked and it seems like a peculiar error of Mac. Do you know how to overcome it?

**Comment by Naeemkh** [comment]
Hi @fbargaglistoffi, thanks for letting us know. CausalGPS is not directly dependent on the "mnormt" package. However, your problem might be related to the content of the  `~/.R/Makevars` file. I would suggest:

1) Try to install `mnromt` package first. 
2) Double-check the content of `~/.R/Makevars`

**Comment by Naeemkh** [comment]
Hi @fbargaglistoffi , 
Please install gcc and modify the Makevars file. 

```
brew install gcc
```
Find the version and path of the newly installed gcc and modify the Makevars file.

```
CC = gcc-11
CXX = g++-11
FLIBS = -L/usr/local/lib/gcc/11/gcc/x86_64-apple-darwin19.6.0/11.0.0 -L/usr/local/lib/gcc/11 -lgfortran -lquadmath -lm
```

Your `gcc` version (11) and platform ("x86_64-apple-darwin19.6.0") might be different than what we have here.
