### ISSUE TITLE
`transformers` parameter in generate_pseudo_pop() 

### ISSUE THREAD

**Issue by m-qin** [fasrc/CausalGPS#144]
Hello! I had a couple clarifications/questions about the `transformers` parameter in generate_pseudo_pop().

1. Can I only enter "pow2" and "pow3" as transformers, or can I also enter common functions like "sqrt" or a function I define beforehand like "logit"? I'm a little confused from the documentation, which says there are [only?] 2 available transformers but users may enter a customized function.
2. If the algorithm uses these transformations to improve covariate balance, are the covariates transformed in the output of generate_pseudo_pop(), which might be called `matched_pop$pseudo_pop`? Are `matched_pop$original_corr_results` and `matched_pop$adjusted_corr_results` evaluated on the transformed covariates? Is it recorded anywhere which transformations were used?

Thanks!

_Originally posted by @m-qin in https://github.com/fasrc/CausalGPS/discussions/142_

**Comment by Naeemkh** [comment]
See #142
