### ISSUE TITLE
Permanent solution for temporal fix of test data

### ISSUE THREAD

**Issue by Naeemkh** [fasrc/CausalGPS#65]
With adding a new feature, the original data has two more columns. This causes a problem with test data (loaded in R/sysdata.rda). We need to add those two columns (see test-absolute_weighted_corr_fun.R and test-check_covar_balance.R) into the test data and remove the temporal fix. 
For how to handle this situation, please read "Steps for using precomputed data during the test
" section from the following link:
https://fasrc.github.io/CausalGPS/articles/testing_the_package.html

**Comment by kevinxsu** [comment]
Correct link: https://fasrc.github.io/CausalGPS/articles/Testing-the-Package.html
