### ISSUE TITLE
Discrepancy between optimized_compile = TRUE vs. False.

### ISSUE THREAD

**Issue by wxwx1993** [fasrc/CausalGPS#91]
[test_causalGPS_optimized_compile.R.zip](https://github.com/fasrc/CausalGPS/files/6984714/test_causalGPS_optimized_compile.R.zip)

**Comment by Naeemkh** [comment]
@wxwx1993, thanks for sharing a reproducible example.  Could you please explain what did you expect to see and what the result was?

**Comment by wxwx1993** [comment]
We should expect:

`sort(unique(psuedo_data_uni$row_index)) == sort(unique(psuedo_data_opt_pos$row_index))
`

output all TRUE.

**Comment by Naeemkh** [comment]
<img width="801" alt="Screen Shot 2021-08-13 at 4 10 32 PM" src="https://user-images.githubusercontent.com/6773835/129418794-847f04cb-48bd-48bc-bf51-cd36cde1aac1.png">

I just checked, all of them are TRUE. Could you double check the code.

**Comment by wxwx1993** [comment]
[test_causalGPS_optimized_compile-1.R.zip](https://github.com/fasrc/CausalGPS/files/6985247/test_causalGPS_optimized_compile-1.R.zip)

**Comment by wxwx1993** [comment]
> <img alt="Screen Shot 2021-08-13 at 4 10 32 PM" width="801" src="https://user-images.githubusercontent.com/6773835/129418794-847f04cb-48bd-48bc-bf51-cd36cde1aac1.png">
> 
> I just checked, all of them are TRUE. Could you double check the code.

Is not the output with length approximately 50, why yours is only 14

**Comment by Naeemkh** [comment]
Please re-run the attached code.
[test_causalGPS_optimized_compile-1_NK.R.zip](https://github.com/fasrc/CausalGPS/files/6985320/test_causalGPS_optimized_compile-1_NK.R.zip)

**Comment by wxwx1993** [comment]
> sort(unique(psuedo_data_uni$row_index)) == sort(unique(psuedo_data_opt_pos$row_index))
 [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[18] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[35] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[52] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
Warning message:
In sort(unique(psuedo_data_uni$row_index)) == sort(unique(psuedo_data_opt_pos$row_index)) :
  longer object length is not a multiple of shorter object length
